version: '3.8'
services:
  web: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - .env
  # nginx: 
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:80"
  #   restart: always
  #   depends_on:
  #     - web